# Generated by Django 4.2.1 on 2023-07-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='fprice',
            new_name='fqty',
        ),
    ]
